# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later

lane :push_to_pod do
  pod_push(path: "NFCommentSDK.podspec", repo: "neteaseyouliao", sources: ["https://github.com/NetEaseYouliao/Specs.git", "https://github.com/CocoaPods/Specs.git"], allow_warnings: true, use_libraries: true)
end
